### ISSUE TITLE
Neshta.Virus.FileInfector.DDS

### ISSUE THREAD

**Issue by Shanti099** [Svxy/DupliSweep#2]
Why VirusTotal says that it have Neshta.Virus.FileInfector.DDS?

**Comment by Svxy** [comment]
That is most definitely a false positive by malware bytes as that is their detection name, but it could be caught due to the fact the script indexes file hashes within a set, essentially temporarily storing them and taking control of them when duplicates are removed by the user.

My virustotal scan didn't come back positive though;

![Screenshot 2023-06-26 095528](https://github.com/Svxy/DupliSweep/assets/93295911/c1f4b6c6-7a2b-4327-834c-26a1aba980cf)

If you're still skeptical about my executable, feel free to analyze and compile the code yourself. : )
